### ISSUE TITLE
Tool Repairing/Custom Anvil Smithing Recipes

### ISSUE THREAD

**Issue by Rebel459** [Hantonik/AnvilAPI#25]
### Feature description:

Would be great to be able to add more repair recipes like the ones used in vanilla, eg making a recipe that lets you repair a netherite sword using netherite scrap. Would be a cool feature for all versions imo, but if you want a specific version to target Fabric 1.20.1 would be great. Thanks!

**Comment by ghost** [comment]
(I'm not very knowledgable of Github so I'm not sure if this comments area is meant for this) I definently would love this feature as well. I've wanted to wipe out mending from my modpack and replace it with something progression/material based but zero mods on fabric really touch this subject. I know it must be possible since there are mods that interact with the repairs system. I was hoping this mod would do that but it seems not to.

**Comment by Rebel459** [comment]
hey @comacrow I suggest you take a look at Enchantery (Fabric, 1.20.1, available on Modrinth). May not be what you're after exactly but it's highly customisable through datapacks / tags and does a similar thing with mending/repairing to what you described

**Comment by Hantonik** [comment]
@Rebel459 This functionality has already been implemented. For more details, please refer to the documentation provided [here](https://github.com/Hantonik/AnvilAPI/wiki/Usage-in-Modpack#create-repair-recipe).

@comacrow I believe this mod can help you with the first part. If you wish to remove mending from your modpack, you can achieve this using the functionality outlined [here](https://github.com/Hantonik/AnvilAPI/wiki/Usage-in-Modpack#disable-enchantment-recipe). This feature has been available since version `5.1.1.0-beta`.

Sorry for the late response. I hope that, nonetheless, I was able to help.
