### ISSUE TITLE
Is this mod able to replace vanilla recipes?

### ISSUE THREAD

**Issue by PersuGames** [Hantonik/AnvilAPI#9]
I'm currently looking for a mod that will help me replace a vanilla recipe for repair of an item to a different one, is this mod only able to make a second recipe or can I also remove the old one/ replace the old one?

**Comment by Hantonik** [comment]
AnvilAPI currently doesn't provide the ability to replace or remove anvil recipes.

**Comment by PersuGames** [comment]
Would love to see you add this functionality, so vanilla recipes can be replaced by new anvilapi-related ones just by using the correct filename while also adding a naming scheme to all vanilla recipes as from what I understand they dont currently have one like that. (for example: merge_stone_pickaxe.json and if you leave the file blank it would remove merging two stone pickaxes from the anvil recipes, or repair_stone_pickaxe.json one could replace cobblestone in the recipe to use a different item to repair the tool with and even possibly adjust how much durability it would repair)

**Comment by Hantonik** [comment]
I can't add this functionality in the way you described due to how Mojang deals with vanilla anvil recipes. However, I've added an option to disable specific repair and enchantment recipes by including them in the `disabled_vanilla_recipes.json` config file.

Example: 
```json
{
  "repair": [
    "minecraft:diamond_sword"
  ],
  "repairItems": [],
  "enchantments": []
}
```
As you can see, this configuration would disable all repair recipes for **Diamond sword**, which means you wouldn't be able to repair a **Diamond sword** with diamonds or combine two of them for repair.

If you want to disable tool repair with only one specific item, you can do it as shown in the example provided:
```json
{
  "repair": [
    {
      "baseItem": "minecraft:wooden_axe",
      "repairItem": "minecraft:birch_planks"
    }
  ],
  "repairItems": [],
  "enchantments": []
}
```
This configuration would disable repair recipe for **Wooden axe**, but only when using **Birch planks**, while all other types of planks will still work.

If you wish to disable all repair recipes that require a specific repair item, you can do so as shown in the example below:
```json
{
  "repair": [],
  "repairItems": [
    "minecraft:gold_ingot"
  ],
  "enchantments": []
}
```
This configuration would disable all repair recipes that require use of **Gold ingots** as a repair material.

If you have a need to disable enchantment recipes using a book with specific enchantment, you can do so using this example:
```json
{
  "repair": [],
  "repairItems": [],
  "enchantments": [
    "minecraft:sharpness"
  ]
}
```
This configuration would disable all enchantment recipes that use a book with any level of the **Sharpness** enchantment. However, you can specify the level to be excluded from use.
Example:
```json
{
  "repair": [],
  "repairItems": [],
  "enchantments": [
    {
      "enchantment": "minecraft:sharpness",
      "level": 3
    }
  ]
}
```
In this example, only the enchantment recipes that require a book with **Sharpness III** are disabled.

You can also disable the enchantment recipe for a specific item with a specific enchantment. You can do it as shown in this example:
```json
{
  "repair": [],
  "repairItems": [],
  "enchantments": [
    {
      "baseItem": "minecraft:iron_chestplate",
      "enchantment": "minecraft:fire_protection"
    }
  ]
}
```
Here, the enchanting recipe for an **Iron Chestplate** with a **Fire Protection** enchantment of any level would be disabled. However, you can also specify the enchantment level to be excluded from use just by adding `"level": <level>`.

If you prefer, you can use an **Ingredient** instead of a reference to item, as in a regular recipe.
Example: 
```json
{
  "repair": [],
  "repairItems": [
    {
      "tag": "forge:ingots"
    }
  ],
  "enchantments": []
}
```
Here, instead of referencing a specific item, I used a **tag** to refer to all items contained within it.

However, if you're a **Mod developer**, you might be interested in the methods in class `hantonik.anvilapi.utils.AADisabledRecipes` that allow you to disable repair and enchantment recipes directly from code.

If you have any questions, feel free to let me know!

**Comment by robosoup2** [comment]
Hi, thanks for all this great work!
I wanted to ask if/how these features can be used to disable the combining of 2 enchanted books?
I tried a few ways but they didn't work, sorry if i'm missing anything obvious

> {
>   "repair": [
>     {
>       "baseItem": "minecraft:enchanted_book",
>       "repairItem": "minecraft:enchanted_book"
>     }
>   ],
>   "repairItems": [],
>   "enchantments": []
> }
> 

neither of these worked

> {
>   "repair": [
>     "minecraft:enchanted_book"
>   ],
>   "repairItems": [],
>   "enchantments": []
> }

**Comment by Hantonik** [comment]
AnvilAPI currently doesn't offer the ability to disable the combination of two specific enchantments, but the concept seems worthy of consideration.

**Comment by Hantonik** [comment]
Starting from version `5.1.1.0-beta`, you have the option to disable enchantment combining recipes using the following method:
```json
{
  "repair": [],
  "repairItems": [],
  "enchantments": [
    {
      "combining": [
        {
          "enchantment": "minecraft:bane_of_arthropods"
        },
        {
          "enchantment": "minecraft:looting",
          "level": 3
        }
      ]
    }
  ]
}
```
In this example, the combination of an enchantment book containing the **Bane of Arthropods** enchantment at any level with a book containing the **Looting III** enchantment will be disabled.

You can also disable leveling up a book with a specific enchantment. Example:
```json
{
  "repair": [],
  "repairItems": [],
  "enchantments": [
    {
      "combining": [
        {
          "enchantment": "minecraft:protection",
          "level": 2
        }
      ]
    }
  ]
}
```
In this case, the enchantment **Protection II** will be excluded from further leveling, while levels **I** and **III** will still be eligible for enhancement.

Hope that helps!

**Comment by robosoup2** [comment]
wow that was fast, nice work!! I was personally just trying to disable combining or leveling of all enchantments, is there a way to do that or would I have to just make a bunch of recipes? no worries if not!

**Comment by Hantonik** [comment]
It was planned, but, for now, I'm afraid you'll have to disable all recipes manually.
